services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      PORT: "8080"
      GAME_SERVERS: ${GAME_SERVERS:?}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:?}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:?}

  game-server:
    build:
      context: .
      dockerfile: Dockerfile.game
    environment:
      PORT: "8081"
      DATABASE_URL: ${DATABASE_URL:?}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:?}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:?}
